workflows:
  default-workflow:
    name: SEAON HR - Android APK Build
    instance_type: linux_x2
    max_build_duration: 60
    triggering:
      events:
        - push
      branch:
        include_patterns:
          - main
    environment:
      flutter: stable
      java: 11
      gradle: 8.4.1
    android:
      gradle_wrapper_path: android/gradle/wrapper/gradle-wrapper.jar
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
